version: '3.7'

services:
  web:
    image: php:apache
    container_name: web
    volumes:
      - C:/Users/gantawitb/Documents/kku-report/:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: TDyutdYdyudRTYDsEFOPI  
      MYSQL_DATABASE: epm_report  
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - 8081:80

volumes:
  db_data:
